# Generated by Django 5.1.7 on 2025-03-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('url', models.URLField()),
                ('user_agent', models.TextField()),
                ('element', models.CharField(blank=True, max_length=50, null=True)),
                ('element_id', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
